### ISSUE TITLE
大佬 如若想要修改地图  应该修改哪写文件

### ISSUE THREAD

**Issue by 2642543078** [www-Ye/generative_agents_chinese#10]

**Comment by www-Ye** [comment]
修改地图主要在environment/frontend_server/static_dirs/assets/the_ville文件夹下

**Comment by 2642543078** [comment]
大佬我知道修改地图在the_ville 我这里想要做一个自定义地图 但是在地图的区域场所以及物品的数字不是会对应什么物品嘛 但是这个数字是怎么生成的 地图编辑器tiled我用了 并不知道怎么生成对应的物品场所的数字

**Comment by 2642543078** [comment]
大佬 我知道数字用的tiled地图编辑器 
![image](https://github.com/www-Ye/generative_agents_chinese/assets/126142230/67295fee-e4da-403e-8e23-003c346cc1f3)
我把地图改了 我想说地图编辑器他会自己生成的数字 我想把数字对应上我的物品 就是怎么看才能知道这个数字对应的物品是不是我的这个数字

**Comment by www-Ye** [comment]
这个我也不是特别了解

**Comment by 2642543078** [comment]
![image](https://github.com/www-Ye/generative_agents_chinese/assets/126142230/9aad198c-a5c0-46d0-90ce-4acfb6d9c288)
看马桶的坐标就是（3，3）
![image](https://github.com/www-Ye/generative_agents_chinese/assets/126142230/667996da-3bcb-42bb-ab62-cd40eedfd220)
但是这个坐标就是显示（4，2）哪里的问题
