### ISSUE TITLE
交互

### ISSUE THREAD

**Issue by 2642543078** [www-Ye/generative_agents_chinese#11]
博主 如果我想要做一个跟虚拟人交互的那样一个功能 就是开放一个端口嘛 一个协议 但是我想要把虚拟人的记忆就是我想跟某一个小镇里的虚拟人交互对话这个记忆应该怎么加呢 博主提点一下 谢谢！！！

**Comment by www-Ye** [comment]
是指加上外部接口和虚拟人之间对话的记忆么

**Comment by 2642543078** [comment]
对是的 加一个外部接口和虚拟人对话

**Comment by www-Ye** [comment]
我觉得可以在reverie\backend_server\persona\memory_structures\associative_memory.py里加一个会话存储的方法，每次会话完成调用方法把会话和对应embedding存在数据库里

**Comment by 2642543078** [comment]
但是我想要加入这个虚拟人的记忆 比如我们真实的人是跟虚拟人交互的 那这个虚拟人有一个自己的身份 这部分的记忆在associative_memory.py中也有么

**Comment by www-Ye** [comment]
associative_memory.py应该是存储agent个人信息的，想添加与真实人交互的记忆得自己新写一个方法来存储

**Comment by 2642543078** [comment]
associative_memory.py应该是存储agent个人信息的, 那这样的话不就达到我的目的了么 那这样我每次调用这个函数他都会调用agent的个人信息 这样agent对话不就是跟他自己相关的了么 我想说哪个短期记忆存储的和长期记忆存储的有什么不一样吗 都存储的是什么

**Comment by www-Ye** [comment]
短期记忆是可以直接放在上下文context里，长期记忆需要额外存储比如向量库，在需要时检索长期记忆

**Comment by 2642543078** [comment]
错了 我想要开放一个外部接口 这个接口的功能是可以和虚拟人进行对话 然后我想要让虚拟人有自己我们定义的他是一个什么虚拟角色嘛就这个记忆 我想说怎么封装
