### ISSUE TITLE
新添

### ISSUE THREAD

**Issue by 2642543078** [www-Ye/generative_agents_chinese#5]
如果想要新填一些角色 加哪些文件

**Comment by www-Ye** [comment]
以三人小镇为例，environment/frontend_server/storage/base_the_ville_isabella_maria_klaus_zh/personas可以在这个文件夹下与其他几个人物相同的格式添加新的人物文件夹即可

**Comment by 2642543078** [comment]
就以三人小镇为例子 加上几个人物相同的格式的文件夹 不仅仅只需要配置这个吧 应该还需要配置别的文件吗

**Comment by www-Ye** [comment]
还有environment中的0.json设定人物的初始位置

**Comment by 2642543078** [comment]
初始位置在哪里 还有除了这个还有别的文件么
