### ISSUE TITLE
错误

### ISSUE THREAD

**Issue by 2642543078** [www-Ye/generative_agents_chinese#6]
total_expected_min = int(prompt.split("（总持续时间，分钟")[-1]
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: invalid literal for int() with base 10: '以5分钟的间隔描述子任务。\n---\n名字：Kelly Bronson\n年龄：35\n背景故事：Kelly一直想成为一名教师，现在她教育幼儿园。在一周内，她全身心地投入到对学生的教育中，但在周末，她喜欢尝试新的餐厅 和与朋友们出去玩。她非常热情友好，喜欢照顾别人。\n性格：甜美，温柔，细心\n位置：Kelly位于一个较旧的公寓，有以下区域： { 厨房，卧室，餐厅，阳台，办公室，浴室，客厅，走廊}

**Comment by www-Ye** [comment]
尝试一下重新run 一定步数还会有相同报错出现么

**Comment by 2642543078** [comment]
有的

**Comment by 2642543078** [comment]
在处理run_gpt_prompt报错 在390行报错 这里的378-390行是否有逻辑问题

**Comment by 2642543078** [comment]
老显示UnboundLocalError: cannot access local variable 'k' where it is not associated with a value这个k值未赋值

**Comment by www-Ye** [comment]
你是用chatgpt模型来实现模拟的么，这里如果输出格式与解析格式不同就会无法解析导致报错

**Comment by 2642543078** [comment]
代码的376_输出是cr['08:00 AM ~ 09:00 AM期间列出Isabella在霍布斯咖啡馆里工作,收拾店铺并准备迎接新的一天的子任务(总持续时间,分钟):', '', ' Isabella在霍布斯咖啡馆里工作,收拾店铺并准备迎接新的一天。 (持续时间,分钟:30,剩余分钟:30)',]太多只截取一部分 
那就会报上面那个错误
