### ISSUE TITLE
重复

### ISSUE THREAD

**Issue by 2642543078** [www-Ye/generative_agents_chinese#8]
在他们的Current Conversation中生成的对话是重复 应该去哪个文件去追溯

**Comment by www-Ye** [comment]
可以修改reverie/backend_server/persona/prompt_template/v2_zh/create_conversation_v2.txt和generate_next_convo_line_v1.txt中的prompt

**Comment by 2642543078** [comment]
如果想要让他们的谈话围绕一个主题进行谈话应该修改那个提示模板文件呢

**Comment by 2642543078** [comment]
如果就是我想要他们进行对话的次数在一天中增多应该怎么改呢
